### ISSUE TITLE
Fix validation message in single-entry calculator.

### ISSUE THREAD

**Issue by jepusto** [jepusto/SingleCaseES#23]
Enter the following data in the single-entry calculator:
Phase A: 4 3 5 3
Phase B: 0 3 101

The validation error message
> "For percentage scale, values must be between 0 and 100."

appears twice.

**Comment by DMSwan** [comment]
I'm not 100% certain this isn't working a intended in some sense because if look here:

https://shiny.rstudio.com/articles/validation.html

A lot of their messages are showing up twice, but I'll see what I can do.

**Comment by DMSwan** [comment]
This bug is somehow related to this line:

dat$compute <- all(sapply(dat, function(x) sum(!is.na(x)) >= 3))

As long as this stays FALSE, say with data like this:
Phase A: 5 3
Phase B: 0 3 101

Where Phase A has only two values, then the error only shows once. As soon as it flips to TRUE, the error shows up twice. 

The validate is getting called twice somehow. I'm not sure I can fix this. One possible solution may be to turn the dat$compute check into a validate() call instead, but I'm not going to do it tonight. Bed time.

**Comment by jepusto** [comment]
It looks like the validation messages propogate to any output that uses the reactive object ES(). But output$result seems to be the only thing that calls ES(). I'm confused.
