### ISSUE TITLE
Adding ADISO functions

### ISSUE THREAD

**Issue by austinj** [jepusto/SingleCaseES#41]
I've been working on putting the ADISO code for alternating treatments designs from [Manolov and Onghena (2018)](https://github.com/jepusto/SingleCaseES/files/4893602/met_23_3_480.pdf) into functions, and wondered if you thought this would be a good addition to this package. I've modeled the arguments and what they want off of `effect_size_MB()` from `scdhlm`. The function for the version of ADISO that performs all comparisons in the same order is already written and working (see [supplement](https://github.com/jepusto/SingleCaseES/files/4893599/MET-2016-0540.pdf), page 8), returning a list ala `effect_size_MB()`.

Also, this would be my first contribution to someone else's repository, so noob alert.

**Comment by jepusto** [comment]
Hi Austin! I appreciate your efforts and I'm certainly open to contributions to the package, in principle. However, I need to set some parameters about the set of methods that are within scope of this package, both so that the range of options doesn't get too overwhelming for potential users and so that it's possible to maintain the code-base over the medium- to long-ish term. So for new contributions, here is what I'm thinking:

1. Case-level effect size measure
2. Relevant for one or more types of SCEDs
3. Comes with a defensible measure of uncertainty (standard error and/or confidence interval). This can be approximate (as is the case for LRRd, LRRi, LOR) and have assumptions attached (as with all of the effect size measures currently in the package), so long as the assumptions are stated. 

Of course, the package currently does include several non-overlap measures that don't come with standard errors (PND, PAND, IRD, Tau-U). My rationale for keeping them in is that researchers may need to calculate them a) to appease reviewers or b) to understand how they're different (and IMO, fundamentally flawed) compared to the other available metrics. 

So in the case of ADISO, it passes criteria (1) and (2) but AFAIK it fails on (3). So I'm open to adding it if a defensible standard error can be supplied (which is probably on the original developers).

Again, I do appreciate the offer to contribute to the package. I really should have articulated the scope for further contributions as part of the documentation. I'll add that to the to-do list. I'm also open to discussion on the exact scope, if you've got arguments for taking a different approach.

**Comment by austinj** [comment]
That makes total sense; I appreciate the response!
