### ISSUE TITLE
Add unit tests against Pustejovsky (2015)

### ISSUE THREAD

**Issue by jepusto** [jepusto/SingleCaseES#9]
Add unit tests that validate functions against the first two examples in Pustejovsky (2015; Psych Methods).

**Comment by DMSwan** [comment]
I finished this with push b8c5219813cf73e126bd9f0b0dd353d159cddf0c. These unit test is a little ugly because the arguments to calc_ES aren't uniform across effect sizes. The "improvement" direction of the various effect sizes wasn't uniform within Pustejovsky (2015) with regard to the way you've termed them inside of this package, and SMD wasn't bias corrected while LRR was, so I had to call each effect size separately to reflect the way that the different effect sizes arguments varied. I would be willing to believe this could break at some point and it might be hard to understand why. But I did it.
